# CS2-Coach Konfiguration
coach_subfolder: CS2-Coach
demo_folder: D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\game\csgo\replays
discord_webhook: ''
language: de
obsidian_vault_path: C:/Users/Home/Desktop/cs2-coach
player_name: deej0t
steam_id: ''
